"""new field in user model 

Revision ID: 020bdb45bd81
Revises: 59968822f1da
Create Date: 2021-03-13 21:48:55.510781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020bdb45bd81'
down_revision = '59968822f1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
